version: '3.1'

volumes:
  mysql_storage:

services:
  db:
    image: mysql
    container_name: mysql
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: translator